  // Data for therapeutic areas and proteins
  export const areaProteinData: { [key: string]: { name: string; id: string }[] } = {
    Respiratory: [
      { name: "Cystic Fibrosis Transmembrane Conductance Regulator (CFTR)", id: "P13569" },
    { name: "DNAI1 (Dynein Axonemal Intermediate Chain 1)", id: "Q13409" },
    { name: "DNAH5 (Dynein Axonemal Heavy Chain 5)", id: "Q8WZ42" },
    { name: "DNAH11 (Dynein Axonemal Heavy Chain 11)", id: "Q96DT5" },
    { name: "CCDC39 (Coiled-Coil Domain Containing Protein 39)", id: "Q9P2D7" },
    { name: "CCDC40 (Coiled-Coil Domain Containing Protein 40)", id: "Q5SZD1" },
    { name: "SFTPB (Surfactant Protein B)", id: "P07988" },
    { name: "SFTPC (Surfactant Protein C)", id: "P11686" },
    { name: "ABCA3 (ATP-Binding Cassette Subfamily A Member 3)", id: "Q99758" },
    { name: "SERPINA1 (Alpha-1 Antitrypsin)", id: "P01009" },
    { name: "ENG (Endoglin)", id: "P17813" },
    { name: "ACVRL1 (Activin A Receptor Type II-Like 1)", id: "P37023" },
    { name: "CSF2RA (Colony Stimulating Factor 2 Receptor Alpha Subunit)", id: "P15509" },
    { name: "BMPR2 (Bone Morphogenetic Protein Receptor Type 2)", id: "Q13873" },
    { name: "CAV1 (Caveolin-1)", id: "Q03135" },
    { name: "KCNK3 (Potassium Channel Subfamily K Member 3)", id: "Q9Y257" },
    { name: "VHL (Von Hippel-Lindau Tumor Suppressor)", id: "P40337" },
    { name: "TERT (Telomerase Reverse Transcriptase)", id: "O14746" },
    { name: "RTEL1 (Regulator of Telomere Elongation Helicase 1)", id: "Q9NZ71" },
    { name: "TSC1 (Tuberous Sclerosis Complex 1)", id: "Q92574" },
    { name: "TSC2 (Tuberous Sclerosis Complex 2)", id: "P49815" },
    { name: "FOXC2 (Forkhead Box C2)", id: "O43612" },
    { name: "GATA6 (GATA Binding Protein 6)", id: "Q92908" },
    { name: "CSF2RB (Colony Stimulating Factor 2 Receptor Beta Subunit)", id: "P32927" },
    { name: "PHOX2B (Paired-Like Homeobox 2B)", id: "Q99453" },
    { name: "SFTPA1 (Surfactant Protein A1)", id: "Q8IWL2" },
    { name: "SFTPA2 (Surfactant Protein A2)", id: "Q8IWL1" },
    { name: "EIF2AK4 (Eukaryotic Translation Initiation Factor 2 Alpha Kinase 4)", id: "Q9NZJ5" },
    { name: "FLCN (Folliculin)", id: "Q8N688" },
    { name: "NRP1 (Neuropilin-1)", id: "O14786" },
    { name: "MUC5B (Mucin 5B)", id: "Q9HC84" },
    { name: "HPS1 (Hermansky-Pudlak Syndrome Protein 1)", id: "Q92902" },
    { name: "CTC1 (CST Complex Subunit 1)", id: "Q9H6J1" },
    { name: "TERC (Telomerase RNA Component)", id: "P49746" },
    { name: "HPS3 (Hermansky-Pudlak Syndrome Protein 3)", id: "Q9NZD8" },
    { name: "RET (Proto-oncogene tyrosine-protein kinase receptor Ret)", id: "P07949" },
    { name: "ZFPM2 (Zinc Finger Protein, FOG Family Member 2)", id: "O60759" },
    { name: "RSPH4A (Radial Spoke Head 4 Homolog A)", id: "Q5TD94" },
    ],
    Renal:[
      { name: "Polycystin-1 (PKD1)", id: "PKD1" },
    { name: "Polycystin-2 (PKD2)", id: "PKD2" },
    { name: "Fibrocystin/Polyductin (PKHD1)", id: "PKHD1" },
    { name: "Collagen Alpha-3(IV) Chain (COL4A3)", id: "COL4A3" },
    { name: "Collagen Alpha-4(IV) Chain (COL4A4)", id: "COL4A4" },
    { name: "Collagen Alpha-5(IV) Chain (COL4A5)", id: "COL4A5" },
    { name: "Sodium-Potassium-Chloride Cotransporter (NKCC2, SLC12A1)", id: "SLC12A1" },
    { name: "Renal Outer Medullary Potassium Channel (ROMK, KCNJ1)", id: "KCNJ1" },
    { name: "Chloride Channel Kb (CLCNKB)", id: "CLCNKB" },
    { name: "Thiazide-Sensitive Sodium-Chloride Cotransporter (NCC, SLC12A3)", id: "SLC12A3" },
    { name: "Nephrocystin-1 (NPHP1)", id: "NPHP1" },
    { name: "Inversin (NPHP2, INVS)", id: "INVS" },
    { name: "Nephrocystin-3 (NPHP3)", id: "NPHP3" },
    { name: "Nephrocystin-4 (NPHP4)", id: "NPHP4" },
    { name: "Nephrocystin-5 (NPHP5, IQCB1)", id: "NPHP5" },
    { name: "Nephrocystin-6 (NPHP6, CEP290)", id: "NPHP6" },
    { name: "Nephrin (NPHS1)", id: "NPHS1" },
    { name: "Podocin (NPHS2)", id: "NPHS2" },
    { name: "WT1 (Wilms Tumor 1)", id: "WT1" },
    { name: "Alpha-Galactosidase A (GLA)", id: "GLA" },
    { name: "Chloride Channel 5 (CLCN5)", id: "CLCN5" },
    { name: "Low-Density Lipoprotein Receptor-Related Protein 2 (LRP2)", id: "LRP2" },
    { name: "Cystinosin (CTNS)", id: "CTNS" },
    { name: "Ectonucleotide Pyrophosphatase/Phosphodiesterase 1 (ENPP1)", id: "ENPP1" },
    { name: "Sodium-Phosphate Cotransporter 2 (SLC34A1)", id: "SLC34A1" },
    { name: "Alanine-Glyoxylate Aminotransferase (AGXT)", id: "AGXT" },
    { name: "Glyoxylate Reductase/Hydroxypyruvate Reductase (GRHPR)", id: "GRHPR" },
    { name: "Anion Exchanger 1 (AE1, SLC4A1)", id: "SLC4A1" },
    { name: "Carbonic Anhydrase II (CA2)", id: "CA2" },
    { name: "UMOD (Uromodulin)", id: "UMOD" },
    { name: "Tamm-Horsfall Protein (THP)", id: "THP" },
    { name: "CD2-Associated Protein (CD2AP)", id: "CD2AP" },
    { name: "C5ORF42 (Involved in Joubert Syndrome 17)", id: "C5ORF42" },
    { name: "AHI1 (Abelson Helper Integration Site 1)", id: "AHI1" },
    { name: "Meckelin (TMEM67)", id: "TMEM67" },
    { name: "PAX2 (Paired Box Protein Pax-2)", id: "PAX2" },
    { name: "Epithelial Sodium Channel Subunit Beta (SCNN1B)", id: "SCNN1B" },
    { name: "Epithelial Sodium Channel Subunit Gamma (SCNN1G)", id: "SCNN1G" },
    { name: "Phosphatidylinositol 4,5-bisphosphate 5-phosphatase (OCRL)", id: "OCRL" },
    { name: "Calcium-Sensing Receptor (CASR)", id: "CASR" },
    { name: "4-Hydroxy-2-oxoglutarate Aldolase (HOGA1)", id: "HOGA1" },
    { name: "SLC3A1 (Neutral and Basic Amino Acid Transporter)", id: "SLC3A1" },
    { name: "SLC7A9 (B^0,+-Type Amino Acid Transporter)", id: "SLC7A9" },
    { name: "Barttin (BSND)", id: "BSND" },
    { name: "Epithelial Sodium Channel Subunit Alpha (SCNN1A)", id: "SCNN1A" },
    { name: "Hepatocyte Nuclear Factor 1 Beta (HNF1B)", id: "HNF1B" },
    { name: "EYA Transcriptional Coactivator and Phosphatase 1 (EYA1)", id: "EYA1" },
    { name: "Sodium/Potassium-Transporting ATPase Subunit Alpha-1 (ATP1A1)", id: "ATP1A1" },
    { name: "Magnesium Transporter Protein 1 (CNNM2)", id: "CNNM2" },
    { name: "Claudin-16 (CLDN16)", id: "CLDN16" },
    { name: "Phospholipase C Epsilon 1 (PLCE1)", id: "PLCE1" },
    { name: "CEP290 (Centrosomal Protein 290)", id: "CEP290" },
    { name: "NPHP1 (Nephrocystin 1)", id: "NPHP1" },
    { name: "BBS1 (Bardet-Biedl Syndrome 1 Protein)", id: "BBS1" },
    { name: "BBS2 (Bardet-Biedl Syndrome 2 Protein)", id: "BBS2" },
    { name: "Sodium Chloride Cotransporter (SLC12A3, NCC)", id: "SLC12A3" },
    { name: "Collagen Alpha-1(IV) Chain (COL4A1)", id: "COL4A1" },
    ],
    Cardiovascular: [
      { name: "Myosin-7", id: "MYH7: P12883" },
    { name: "Troponin T", id: "TNNT2: P45379" },
    { name: "Troponin I", id: "TNNI3: P19429" },
    { name: "Tropomyosin Alpha-1 Chain", id: "TPM1: P09493" },
    { name: "Myosin Binding Protein C", id: "MYBPC3: Q14896" },
    { name: "Actin, Alpha Cardiac Muscle 1", id: "ACTC1: P68032" },
    { name: "Titin", id: "TTN: Q8WZ42" },
    { name: "Lamin A/C", id: "LMNA: P02545" },
    { name: "Desmin", id: "DES: P17661" },
    { name: "Sodium Voltage-Gated Channel Alpha Subunit 5", id: "SCN5A: Q14524" },
    { name: "Phospholamban", id: "PLN: P26678" },
    { name: "Potassium Voltage-Gated Channel Subfamily Q Member 1", id: "KCNQ1: P51787" },
    { name: "Potassium Voltage-Gated Channel Subfamily H Member 2", id: "KCNH2: Q12809" },
    { name: "Calmodulin 1", id: "CALM1: P62158" },
    { name: "Ankyrin 2", id: "ANK2: Q01638" },
    { name: "GPD1-L", id: "Glycerol-3-phosphate dehydrogenase 1-like: Q8N335" },
    { name: "Calcium Voltage-Gated Channel Subunit Alpha1C", id: "CACNA1C: Q13936" },
    { name: "Ryanodine Receptor 2", id: "RYR2: Q92736" },
    { name: "Calsequestrin 2", id: "CASQ2: O14958" },
    { name: "Fibrillin-1", id: "FBN1: P35555" },
    { name: "Transforming Growth Factor Beta Receptor 1", id: "TGFBR1: P36897" },
    { name: "Transforming Growth Factor Beta Receptor 2", id: "TGFBR2: P37173" },
    { name: "Protein Tyrosine Phosphatase Non-Receptor Type 11", id: "PTPN11: Q06124" },
    { name: "Son of Sevenless Homolog 1", id: "SOS1: Q07889" },
    { name: "Low-Density Lipoprotein Receptor", id: "LDLR: P01130" },
    { name: "Apolipoprotein B", id: "ApoB: P04114" },
    { name: "Proprotein Convertase Subtilisin/Kexin Type 9", id: "PCSK9: Q8NBP7" },
    { name: "Collagen Type III Alpha-1 Chain", id: "COL3A1: P02461" },
    { name: "Myosin Heavy Chain 11", id: "MYH11: P35749" },
    { name: "Actin, Alpha-2, Smooth Muscle, Aorta", id: "ACTA2: P62736" },
    { name: "PRKAG2", id: "Protein Kinase AMP-Activated Non-Catalytic Subunit Gamma 2: Q9UGJ0" },
    { name: "Potassium Voltage-Gated Channel Subfamily J Member 2", id: "KCNJ2: P63252" },
    { name: "Jagged 1", id: "JAG1: P78504" },
    { name: "Alpha-Myosin Heavy Chain", id: "MYH6: P13533" },
    { name: "Cardiac Troponin C", id: "TNNC1: P63316" },
    { name: "Nexilin", id: "NEXN: Q96A32" },
    { name: "Dystrophin", id: "DMD: P11532" },
    { name: "Sarcomeric Alpha-Actinin", id: "ACTN2: P35609" },
    { name: "Potassium Voltage-Gated Channel Subfamily KQT Member 4", id: "KCNQ4: O43524" },
    { name: "Sodium Voltage-Gated Channel Beta Subunit 1", id: "SCN1B: Q07699" },
    { name: "Potassium Voltage-Gated Channel Subfamily KQT Member 2", id: "KCNQ2: O43526" },
    { name: "Glycerol-3-phosphate dehydrogenase 1-like", id: "GPD1L: Q8N335" },
    { name: "Connexin-43", id: "GJA1: P17302" },
    { name: "Smooth Muscle Protein 22-alpha", id: "TAGLN: P37802" },
    { name: "Fibulin-4", id: "EFEMP2: Q12805" },
    { name: "Transforming Growth Factor Beta 2", id: "TGFB2: P61812" },
    { name: "Collagen Type I Alpha 2 Chain", id: "COL1A2: P08123" },
    { name: "LDL Receptor-Related Protein 1", id: "LRP1: Q07954" },
    { name: "Plakoglobin", id: "JUP: P14923" },
    { name: "Desmoplakin", id: "DSP: P15924" },
    { name: "Plakophilin-2", id: "PKP2: Q99959" },
    { name: "Tenascin-X", id: "TNXB: P22105" },
    { name: "RAF1 Proto-Oncogene", id: "RAF1: P04049" },
    { name: "T-box Transcription Factor TBX5", id: "TBX5: Q99593" },
    { name: "NK2 Homeobox 5", id: "NKX2-5: Q9H2E0" },
    { name: "Caveolin-3", id: "CAV3: P56539" },
    { name: "Telethonin", id: "TCAP: Q9UBF9" },
    { name: "Tropomyosin Beta", id: "TPM2: P07951" },
    { name: "Desmin", id: "DES: P17661" },
    { name: "Transmembrane Protein 43", id: "TMEM43: Q9BTV4" },
    { name: "Potassium Channel Subfamily Member 11", id: "KCNJ11: Q14654" },
    { name: "Calcium Voltage-Gated Channel Subunit Beta 2", id: "CACNB2: Q08289" },
    { name: "GATA4", id: "Transcription Factor GATA-4: P43694" },
    { name: "SMAD3", id: "Mothers Against Decapentaplegic Homolog 3: P84022" },
    { name: "Collagen Type IV Alpha 1 Chain", id: "COL4A1: P02462" },
    { name: "Apolipoprotein E", id: "ApoE: P02649" },
    { name: "Zic Family Member 3", id: "ZIC3: Q15915" },
    { name: "TBX1", id: "T-box Transcription Factor TBX1: Q99593" },
    { name: "Bone Morphogenetic Protein Receptor Type 2", id: "BMPR2: Q13873" },
    { name: "Endothelin Receptor Type A", id: "EDNRA: P25101" },
    { name: "PITX2", id: "Paired Like Homeodomain 2: Q99697" },
    { name: "Fibrillin-2", id: "FBN2: P35556" },
    { name: "NEXN", id: "Nexilin: Q96A32" },
    { name: "Filamin C", id: "FLNC: Q14315" },
    ],
  };