// Data for therapeutic areas and proteins
export const areaProteinData: {
  [key: string]: { name: string; id: string }[];
} = {
  Respiratory: [
    {
      name: "Cystic Fibrosis Transmembrane Conductance Regulator (CFTR)",
      id: "P13569",
    },
    { name: "DNAI1 (Dynein Axonemal Intermediate Chain 1)", id: "Q13409" },
    { name: "DNAH5 (Dynein Axonemal Heavy Chain 5)", id: "Q8WZ42" },
    { name: "DNAH11 (Dynein Axonemal Heavy Chain 11)", id: "Q96DT5" },
    { name: "CCDC39 (Coiled-Coil Domain Containing Protein 39)", id: "Q9P2D7" },
    { name: "CCDC40 (Coiled-Coil Domain Containing Protein 40)", id: "Q5SZD1" },
    { name: "SFTPB (Surfactant Protein B)", id: "P07988" },
    { name: "SFTPC (Surfactant Protein C)", id: "P11686" },
    { name: "ABCA3 (ATP-Binding Cassette Subfamily A Member 3)", id: "Q99758" },
    { name: "SERPINA1 (Alpha-1 Antitrypsin)", id: "P01009" },
    { name: "ENG (Endoglin)", id: "P17813" },
    { name: "ACVRL1 (Activin A Receptor Type II-Like 1)", id: "P37023" },
    {
      name: "CSF2RA (Colony Stimulating Factor 2 Receptor Alpha Subunit)",
      id: "P15509",
    },
    {
      name: "BMPR2 (Bone Morphogenetic Protein Receptor Type 2)",
      id: "Q13873",
    },
    { name: "CAV1 (Caveolin-1)", id: "Q03135" },
    { name: "KCNK3 (Potassium Channel Subfamily K Member 3)", id: "Q9Y257" },
    { name: "VHL (Von Hippel-Lindau Tumor Suppressor)", id: "P40337" },
    { name: "TERT (Telomerase Reverse Transcriptase)", id: "O14746" },
    {
      name: "RTEL1 (Regulator of Telomere Elongation Helicase 1)",
      id: "Q9NZ71",
    },
    { name: "TSC1 (Tuberous Sclerosis Complex 1)", id: "Q92574" },
    { name: "TSC2 (Tuberous Sclerosis Complex 2)", id: "P49815" },
    { name: "FOXC2 (Forkhead Box C2)", id: "O43612" },
    { name: "GATA6 (GATA Binding Protein 6)", id: "Q92908" },
    {
      name: "CSF2RB (Colony Stimulating Factor 2 Receptor Beta Subunit)",
      id: "P32927",
    },
    { name: "PHOX2B (Paired-Like Homeobox 2B)", id: "Q99453" },
    { name: "SFTPA1 (Surfactant Protein A1)", id: "Q8IWL2" },
    { name: "SFTPA2 (Surfactant Protein A2)", id: "Q8IWL1" },
    {
      name: "EIF2AK4 (Eukaryotic Translation Initiation Factor 2 Alpha Kinase 4)",
      id: "Q9NZJ5",
    },
    { name: "FLCN (Folliculin)", id: "Q8N688" },
    { name: "NRP1 (Neuropilin-1)", id: "O14786" },
    { name: "MUC5B (Mucin 5B)", id: "Q9HC84" },
    { name: "HPS1 (Hermansky-Pudlak Syndrome Protein 1)", id: "Q92902" },
    { name: "CTC1 (CST Complex Subunit 1)", id: "Q9H6J1" },
    { name: "TERC (Telomerase RNA Component)", id: "P49746" },
    { name: "HPS3 (Hermansky-Pudlak Syndrome Protein 3)", id: "Q9NZD8" },
    {
      name: "RET (Proto-oncogene tyrosine-protein kinase receptor Ret)",
      id: "P07949",
    },
    { name: "ZFPM2 (Zinc Finger Protein, FOG Family Member 2)", id: "O60759" },
    { name: "RSPH4A (Radial Spoke Head 4 Homolog A)", id: "Q5TD94" },
  ],
  Renal: [
    { name: "Polycystin-1 (PKD1)", id: "PKD1" },
    { name: "Polycystin-2 (PKD2)", id: "PKD2" },
    { name: "Fibrocystin/Polyductin (PKHD1)", id: "PKHD1" },
    { name: "Collagen Alpha-3(IV) Chain (COL4A3)", id: "COL4A3" },
    { name: "Collagen Alpha-4(IV) Chain (COL4A4)", id: "COL4A4" },
    { name: "Collagen Alpha-5(IV) Chain (COL4A5)", id: "COL4A5" },
    {
      name: "Sodium-Potassium-Chloride Cotransporter (NKCC2, SLC12A1)",
      id: "SLC12A1",
    },
    {
      name: "Renal Outer Medullary Potassium Channel (ROMK, KCNJ1)",
      id: "KCNJ1",
    },
    { name: "Chloride Channel Kb (CLCNKB)", id: "CLCNKB" },
    {
      name: "Thiazide-Sensitive Sodium-Chloride Cotransporter (NCC, SLC12A3)",
      id: "SLC12A3",
    },
    { name: "Nephrocystin-1 (NPHP1)", id: "NPHP1" },
    { name: "Inversin (NPHP2, INVS)", id: "INVS" },
    { name: "Nephrocystin-3 (NPHP3)", id: "NPHP3" },
    { name: "Nephrocystin-4 (NPHP4)", id: "NPHP4" },
    { name: "Nephrocystin-5 (NPHP5, IQCB1)", id: "NPHP5" },
    { name: "Nephrocystin-6 (NPHP6, CEP290)", id: "NPHP6" },
    { name: "Nephrin (NPHS1)", id: "NPHS1" },
    { name: "Podocin (NPHS2)", id: "NPHS2" },
    { name: "WT1 (Wilms Tumor 1)", id: "WT1" },
    { name: "Alpha-Galactosidase A (GLA)", id: "GLA" },
    { name: "Chloride Channel 5 (CLCN5)", id: "CLCN5" },
    {
      name: "Low-Density Lipoprotein Receptor-Related Protein 2 (LRP2)",
      id: "LRP2",
    },
    { name: "Cystinosin (CTNS)", id: "CTNS" },
    {
      name: "Ectonucleotide Pyrophosphatase/Phosphodiesterase 1 (ENPP1)",
      id: "ENPP1",
    },
    { name: "Sodium-Phosphate Cotransporter 2 (SLC34A1)", id: "SLC34A1" },
    { name: "Alanine-Glyoxylate Aminotransferase (AGXT)", id: "AGXT" },
    {
      name: "Glyoxylate Reductase/Hydroxypyruvate Reductase (GRHPR)",
      id: "GRHPR",
    },
    { name: "Anion Exchanger 1 (AE1, SLC4A1)", id: "SLC4A1" },
    { name: "Carbonic Anhydrase II (CA2)", id: "CA2" },
    { name: "UMOD (Uromodulin)", id: "UMOD" },
    { name: "Tamm-Horsfall Protein (THP)", id: "THP" },
    { name: "CD2-Associated Protein (CD2AP)", id: "CD2AP" },
    { name: "C5ORF42 (Involved in Joubert Syndrome 17)", id: "C5ORF42" },
    { name: "AHI1 (Abelson Helper Integration Site 1)", id: "AHI1" },
    { name: "Meckelin (TMEM67)", id: "TMEM67" },
    { name: "PAX2 (Paired Box Protein Pax-2)", id: "PAX2" },
    { name: "Epithelial Sodium Channel Subunit Beta (SCNN1B)", id: "SCNN1B" },
    { name: "Epithelial Sodium Channel Subunit Gamma (SCNN1G)", id: "SCNN1G" },
    {
      name: "Phosphatidylinositol 4,5-bisphosphate 5-phosphatase (OCRL)",
      id: "OCRL",
    },
    { name: "Calcium-Sensing Receptor (CASR)", id: "CASR" },
    { name: "4-Hydroxy-2-oxoglutarate Aldolase (HOGA1)", id: "HOGA1" },
    { name: "SLC3A1 (Neutral and Basic Amino Acid Transporter)", id: "SLC3A1" },
    { name: "SLC7A9 (B^0,+-Type Amino Acid Transporter)", id: "SLC7A9" },
    { name: "Barttin (BSND)", id: "BSND" },
    { name: "Epithelial Sodium Channel Subunit Alpha (SCNN1A)", id: "SCNN1A" },
    { name: "Hepatocyte Nuclear Factor 1 Beta (HNF1B)", id: "HNF1B" },
    {
      name: "EYA Transcriptional Coactivator and Phosphatase 1 (EYA1)",
      id: "EYA1",
    },
    {
      name: "Sodium/Potassium-Transporting ATPase Subunit Alpha-1 (ATP1A1)",
      id: "ATP1A1",
    },
    { name: "Magnesium Transporter Protein 1 (CNNM2)", id: "CNNM2" },
    { name: "Claudin-16 (CLDN16)", id: "CLDN16" },
    { name: "Phospholipase C Epsilon 1 (PLCE1)", id: "PLCE1" },
    { name: "CEP290 (Centrosomal Protein 290)", id: "CEP290" },
    { name: "NPHP1 (Nephrocystin 1)", id: "NPHP1" },
    { name: "BBS1 (Bardet-Biedl Syndrome 1 Protein)", id: "BBS1" },
    { name: "BBS2 (Bardet-Biedl Syndrome 2 Protein)", id: "BBS2" },
    { name: "Sodium Chloride Cotransporter (SLC12A3, NCC)", id: "SLC12A3" },
    { name: "Collagen Alpha-1(IV) Chain (COL4A1)", id: "COL4A1" },
  ],
  Cardiovascular: [
    { name: "Myosin-7", id: "MYH7: P12883" },
    { name: "Troponin T", id: "TNNT2: P45379" },
    { name: "Troponin I", id: "TNNI3: P19429" },
    { name: "Tropomyosin Alpha-1 Chain", id: "TPM1: P09493" },
    { name: "Myosin Binding Protein C", id: "MYBPC3: Q14896" },
    { name: "Actin, Alpha Cardiac Muscle 1", id: "ACTC1: P68032" },
    { name: "Titin", id: "TTN: Q8WZ42" },
    { name: "Lamin A/C", id: "LMNA: P02545" },
    { name: "Desmin", id: "DES: P17661" },
    {
      name: "Sodium Voltage-Gated Channel Alpha Subunit 5",
      id: "SCN5A: Q14524",
    },
    { name: "Phospholamban", id: "PLN: P26678" },
    {
      name: "Potassium Voltage-Gated Channel Subfamily Q Member 1",
      id: "KCNQ1: P51787",
    },
    {
      name: "Potassium Voltage-Gated Channel Subfamily H Member 2",
      id: "KCNH2: Q12809",
    },
    { name: "Calmodulin 1", id: "CALM1: P62158" },
    { name: "Ankyrin 2", id: "ANK2: Q01638" },
    { name: "GPD1-L", id: "Glycerol-3-phosphate dehydrogenase 1-like: Q8N335" },
    {
      name: "Calcium Voltage-Gated Channel Subunit Alpha1C",
      id: "CACNA1C: Q13936",
    },
    { name: "Ryanodine Receptor 2", id: "RYR2: Q92736" },
    { name: "Calsequestrin 2", id: "CASQ2: O14958" },
    { name: "Fibrillin-1", id: "FBN1: P35555" },
    {
      name: "Transforming Growth Factor Beta Receptor 1",
      id: "TGFBR1: P36897",
    },
    {
      name: "Transforming Growth Factor Beta Receptor 2",
      id: "TGFBR2: P37173",
    },
    {
      name: "Protein Tyrosine Phosphatase Non-Receptor Type 11",
      id: "PTPN11: Q06124",
    },
    { name: "Son of Sevenless Homolog 1", id: "SOS1: Q07889" },
    { name: "Low-Density Lipoprotein Receptor", id: "LDLR: P01130" },
    { name: "Apolipoprotein B", id: "ApoB: P04114" },
    {
      name: "Proprotein Convertase Subtilisin/Kexin Type 9",
      id: "PCSK9: Q8NBP7",
    },
    { name: "Collagen Type III Alpha-1 Chain", id: "COL3A1: P02461" },
    { name: "Myosin Heavy Chain 11", id: "MYH11: P35749" },
    { name: "Actin, Alpha-2, Smooth Muscle, Aorta", id: "ACTA2: P62736" },
    {
      name: "PRKAG2",
      id: "Protein Kinase AMP-Activated Non-Catalytic Subunit Gamma 2: Q9UGJ0",
    },
    {
      name: "Potassium Voltage-Gated Channel Subfamily J Member 2",
      id: "KCNJ2: P63252",
    },
    { name: "Jagged 1", id: "JAG1: P78504" },
    { name: "Alpha-Myosin Heavy Chain", id: "MYH6: P13533" },
    { name: "Cardiac Troponin C", id: "TNNC1: P63316" },
    { name: "Nexilin", id: "NEXN: Q96A32" },
    { name: "Dystrophin", id: "DMD: P11532" },
    { name: "Sarcomeric Alpha-Actinin", id: "ACTN2: P35609" },
    {
      name: "Potassium Voltage-Gated Channel Subfamily KQT Member 4",
      id: "KCNQ4: O43524",
    },
    {
      name: "Sodium Voltage-Gated Channel Beta Subunit 1",
      id: "SCN1B: Q07699",
    },
    {
      name: "Potassium Voltage-Gated Channel Subfamily KQT Member 2",
      id: "KCNQ2: O43526",
    },
    { name: "Glycerol-3-phosphate dehydrogenase 1-like", id: "GPD1L: Q8N335" },
    { name: "Connexin-43", id: "GJA1: P17302" },
    { name: "Smooth Muscle Protein 22-alpha", id: "TAGLN: P37802" },
    { name: "Fibulin-4", id: "EFEMP2: Q12805" },
    { name: "Transforming Growth Factor Beta 2", id: "TGFB2: P61812" },
    { name: "Collagen Type I Alpha 2 Chain", id: "COL1A2: P08123" },
    { name: "LDL Receptor-Related Protein 1", id: "LRP1: Q07954" },
    { name: "Plakoglobin", id: "JUP: P14923" },
    { name: "Desmoplakin", id: "DSP: P15924" },
    { name: "Plakophilin-2", id: "PKP2: Q99959" },
    { name: "Tenascin-X", id: "TNXB: P22105" },
    { name: "RAF1 Proto-Oncogene", id: "RAF1: P04049" },
    { name: "T-box Transcription Factor TBX5", id: "TBX5: Q99593" },
    { name: "NK2 Homeobox 5", id: "NKX2-5: Q9H2E0" },
    { name: "Caveolin-3", id: "CAV3: P56539" },
    { name: "Telethonin", id: "TCAP: Q9UBF9" },
    { name: "Tropomyosin Beta", id: "TPM2: P07951" },
    { name: "Desmin", id: "DES: P17661" },
    { name: "Transmembrane Protein 43", id: "TMEM43: Q9BTV4" },
    { name: "Potassium Channel Subfamily Member 11", id: "KCNJ11: Q14654" },
    {
      name: "Calcium Voltage-Gated Channel Subunit Beta 2",
      id: "CACNB2: Q08289",
    },
    { name: "GATA4", id: "Transcription Factor GATA-4: P43694" },
    { name: "SMAD3", id: "Mothers Against Decapentaplegic Homolog 3: P84022" },
    { name: "Collagen Type IV Alpha 1 Chain", id: "COL4A1: P02462" },
    { name: "Apolipoprotein E", id: "ApoE: P02649" },
    { name: "Zic Family Member 3", id: "ZIC3: Q15915" },
    { name: "TBX1", id: "T-box Transcription Factor TBX1: Q99593" },
    { name: "Bone Morphogenetic Protein Receptor Type 2", id: "BMPR2: Q13873" },
    { name: "Endothelin Receptor Type A", id: "EDNRA: P25101" },
    { name: "PITX2", id: "Paired Like Homeodomain 2: Q99697" },
    { name: "Fibrillin-2", id: "FBN2: P35556" },
    { name: "NEXN", id: "Nexilin: Q96A32" },
    { name: "Filamin C", id: "FLNC: Q14315" },
  ],
  Oncology: [
    {
      name: "BRCA1 (Breast Cancer Type 1 Susceptibility Protein)",
      id: "P38398",
    },
    {
      name: "BRCA2 (Breast Cancer Type 2 Susceptibility Protein)",
      id: "P51587",
    },
    { name: "TP53 (Tumor Protein P53)", id: "P04637" },
    { name: "CHEK2 (Checkpoint Kinase 2)", id: "O96017" },
    { name: "APC (Adenomatous Polyposis Coli)", id: "P25054" },
    { name: "MLH1 (MutL Homolog 1)", id: "P40692" },
    { name: "MSH2 (MutS Homolog 2)", id: "P43246" },
    { name: "MSH6 (MutS Homolog 6)", id: "P52701" },
    { name: "PMS2 (Postmeiotic Segregation Increased 2)", id: "P54277" },
    { name: "MEN1 (Menin 1)", id: "O00255" },
    {
      name: "RET (Proto-oncogene Tyrosine-Protein Kinase Receptor Ret)",
      id: "P07949",
    },
    { name: "CDKN2A (Cyclin-Dependent Kinase Inhibitor 2A)", id: "P42771" },
    { name: "CDK4 (Cyclin-Dependent Kinase 4)", id: "P11802" },
    { name: "VHL (Von Hippel-Lindau Tumor Suppressor Protein)", id: "P40337" },
    { name: "RB1 (Retinoblastoma Protein)", id: "P06400" },
    { name: "PTEN (Phosphatase and Tensin Homolog)", id: "P60484" },
    { name: "NF1 (Neurofibromin 1)", id: "P21359" },
    { name: "NF2 (Merlin/Schwannomin)", id: "P35240" },
    { name: "TSC1 (Hamartin)", id: "Q92574" },
    { name: "TSC2 (Tuberin)", id: "P49815" },
    { name: "STK11 (Serine/Threonine Kinase 11)", id: "Q15831" },
    { name: "FH (Fumarate Hydratase)", id: "Q16790" },
    { name: "FLCN (Folliculin)", id: "Q8N688" },
    { name: "CDH1 (Cadherin-1)", id: "P12830" },
    { name: "SDHD (Succinate Dehydrogenase Subunit D)", id: "Q10963" },
    { name: "SDHB (Succinate Dehydrogenase Subunit B)", id: "P21912" },
    { name: "ATM (Ataxia Telangiectasia Mutated)", id: "Q13315" },
    { name: "BLM (Bloom Syndrome Protein)", id: "P54132" },
    { name: "FANCA (Fanconi Anemia Group A Protein)", id: "O15360" },
    { name: "FANCD2 (Fanconi Anemia Group D2 Protein)", id: "Q9BXW9" },
    {
      name: "XPA (Xeroderma Pigmentosum Complementation Group A Protein)",
      id: "P23025",
    },
    {
      name: "XPC (Xeroderma Pigmentosum Complementation Group C Protein)",
      id: "Q01831",
    },
    { name: "PTCH1 (Patched 1 Protein)", id: "Q13635" },
    { name: "WRN (Werner Syndrome RecQ Helicase-Like)", id: "Q14191" },
    { name: "CDH1 (E-Cadherin)", id: "P12830" },
    { name: "SDHC (Succinate Dehydrogenase Complex Subunit C)", id: "Q99643" },
    {
      name: "SDHAF2 (Succinate Dehydrogenase Assembly Factor 2)",
      id: "Q9NX58",
    },
    { name: "PALB2 (Partner and Localizer of BRCA2)", id: "Q86YC2" },
    { name: "HOXB13 (Homeobox Protein Hox-B13)", id: "Q92826" },
    { name: "MAX (Myc-Associated Factor X)", id: "P61244" },
    { name: "TMEM127 (Transmembrane Protein 127)", id: "Q9NX22" },
    { name: "CTNNA1 (Catenin Alpha-1)", id: "P35221" },
    { name: "MET (Proto-oncogene c-Met)", id: "P08581" },
    { name: "SMAD4 (Mothers Against Decapentaplegic Homolog 4)", id: "Q13485" },
    {
      name: "BMPR1A (Bone Morphogenetic Protein Receptor Type-1A)",
      id: "P36894",
    },
    { name: "RUNX1 (Runt-Related Transcription Factor 1)", id: "Q01196" },
    {
      name: "BRIP1 (BRCA1 Interacting Protein C-Terminal Helicase 1)",
      id: "Q9BX63",
    },
    { name: "DICER1 (Endoribonuclease Dicer)", id: "Q9UPY3" },
    { name: "GATA2 (GATA-Binding Protein 2)", id: "P23769" },
    { name: "PTCH2 (Patched 2)", id: "Q9Y6C5" },
  ],
  Neurological: [
    { name: "Huntingtin (HTT)", id: "P42858" },
    { name: "Superoxide Dismutase 1 (SOD1)", id: "P00441" },
    { name: "TAR DNA-Binding Protein (TARDBP, TDP-43)", id: "Q13148" },
    { name: "Fused in Sarcoma (FUS)", id: "P35637" },
    { name: "Alpha-Synuclein (SNCA)", id: "P37840" },
    { name: "Parkin (PRKN)", id: "O60260" },
    { name: "DJ-1 (PARK7)", id: "Q99497" },
    { name: "Leucine-Rich Repeat Kinase 2 (LRRK2)", id: "Q5S007" },
    { name: "Amyloid Beta Precursor Protein (APP)", id: "P05067" },
    { name: "Presenilin-1 (PSEN1)", id: "P49768" },
    { name: "Presenilin-2 (PSEN2)", id: "P49810" },
    { name: "Microtubule-Associated Protein Tau (MAPT)", id: "P10636" },
    { name: "Sodium Channel Subunit Alpha Nav1.1 (SCN1A)", id: "P35498" },
    {
      name: "Gamma-Aminobutyric Acid Receptor Subunit Gamma-2 (GABRG2)",
      id: "P18507",
    },
    { name: "Sodium Channel Subunit Beta-1 (SCN1B)", id: "Q07699" },
    { name: "Potassium Channel Subfamily KQT Member 2 (KCNQ2)", id: "O43526" },
    { name: "Dystrophin (DMD)", id: "P11532" },
    { name: "Survival of Motor Neuron 1 (SMN1)", id: "Q16637" },
    { name: "Peripheral Myelin Protein 22 (PMP22)", id: "Q01453" },
    { name: "Myelin Protein Zero (MPZ)", id: "P25189" },
    { name: "Gap Junction Beta-1 Protein (GJB1)", id: "P08034" },
    { name: "Frataxin (FXN)", id: "Q16595" },
    { name: "ATM (Ataxia Telangiectasia Mutated Protein)", id: "Q13315" },
    { name: "Torsin-1A (TOR1A)", id: "O14656" },
    { name: "ATPase Type 13A2 (ATP13A2)", id: "Q9NQ11" },
    { name: "Ataxin-1 (ATXN1)", id: "P54253" },
    { name: "Ataxin-3 (ATXN3)", id: "P54252" },
    { name: "NGF (Nerve Growth Factor)", id: "P01138" },
    { name: "Sodium Channel Subunit Alpha Nav1.4 (SCN4A)", id: "P35499" },
    {
      name: "Calcium Voltage-Gated Channel Subunit Alpha1S (CACNA1S)",
      id: "Q13698",
    },
    {
      name: "CACNA1A (Calcium Channel, Voltage-Dependent, P/Q Type Alpha 1A Subunit)",
      id: "O00555",
    },
    { name: "ABCD1 (ATP-Binding Cassette Subfamily D Member 1)", id: "P33897" },
    { name: "Galactocerebrosidase (GALC)", id: "P54803" },
    { name: "Arylsulfatase A (ARSA)", id: "P15289" },
    { name: "Mitofusin 2 (MFN2)", id: "O95140" },
    { name: "Phytanoyl-CoA Hydroxylase (PHYH)", id: "O14832" },
    { name: "Methyl-CpG Binding Protein 2 (MECP2)", id: "P51608" },
    { name: "ATP7B (Copper-Transporting ATPase 2)", id: "P35670" },
    { name: "Peroxisomal Biogenesis Factor 1 (PEX1)", id: "Q01582" },
    { name: "UBE3A (Ubiquitin-Protein Ligase E3A)", id: "Q05086" },
    { name: "TSC1 (Tuberous Sclerosis Complex 1)", id: "Q92574" },
    { name: "TSC2 (Tuberous Sclerosis Complex 2)", id: "P49815" },
    { name: "Fragile X Mental Retardation Protein 1 (FMR1)", id: "Q06787" },
    { name: "Lissencephaly 1 (LIS1, PAFAH1B1)", id: "P43034" },
    { name: "Doublecortin (DCX)", id: "O43602" },
    { name: "Ribosomal Protein S6 Kinase Alpha-3 (RPS6KA3)", id: "P51812" },
    { name: "Oligophrenin-1 (OPHN1)", id: "Q96NL9" },
    { name: "ARX (Aristaless-Related Homeobox Gene)", id: "Q96QS3" },
    { name: "SURF1 (Surfeit Locus Protein 1)", id: "Q15526" },
    { name: "NADH Dehydrogenase Subunit 1 (MT-ND1)", id: "P03886" },
    { name: "MT-TL1 (Mitochondrial tRNA-Leu)", id: "P00839" },
    { name: "Aspartoacylase (ASPA)", id: "P45381" },
    { name: "Glutaryl-CoA Dehydrogenase (GCDH)", id: "P23378" },
    { name: "Proteolipid Protein 1 (PLP1)", id: "P60201" },
    { name: "Glial Fibrillary Acidic Protein (GFAP)", id: "P14136" },
    { name: "Ataxin-2 (ATXN2)", id: "O00217" },
    { name: "Ataxin-7 (ATXN7)", id: "O15265" },
    {
      name: "Calcium Voltage-Gated Channel Subunit Alpha1A (CACNA1A)",
      id: "O00555",
    },
    { name: "Potassium Channel Subfamily Q Member 3 (KCNQ3)", id: "O43525" },
    { name: "Acetylcholine Receptor Subunit Alpha (CHRNA1)", id: "Q07001" },
    { name: "Rapsyn (RAPSN)", id: "Q13702" },
    {
      name: "Branched-Chain Alpha-Keto Acid Dehydrogenase E1 Alpha Subunit (BCKDHA)",
      id: "P12694",
    },
    {
      name: "Branched-Chain Alpha-Keto Acid Dehydrogenase E1 Beta Subunit (BCKDHB)",
      id: "P21953",
    },
    { name: "Ornithine Transcarbamylase (OTC)", id: "P00480" },
    { name: "Trex1 (Three Prime Repair Exonuclease 1)", id: "Q9NSU2" },
    { name: "Sonic Hedgehog Protein (SHH)", id: "Q15465" },
    { name: "Neurofibromin (NF1)", id: "P21359" },
    { name: "Spastin (SPAST)", id: "Q9UBP0" },
    {
      name: "Mitochondrial Cytochrome C Oxidase Subunit 2 (MT-CO2)",
      id: "P00403",
    },
    { name: "Pyruvate Dehydrogenase E1 Alpha Subunit (PDHA1)", id: "P08559" },
    { name: "TAZ (Tafazzin)", id: "Q16635" },
    { name: "Glutamate Decarboxylase 1 (GAD1)", id: "Q99259" },
    { name: "EMX2 (Empty Spiracles Homeobox 2)", id: "P50502" },
    { name: "UBE3A (Ubiquitin Protein Ligase E3A)", id: "Q05086" },
    { name: "Fukutin (FKTN)", id: "Q9UBW7" },
    { name: "SORL1 (Sortilin-Related Receptor)", id: "Q92673" },
    { name: "SMPD1 (Sphingomyelin Phosphodiesterase 1)", id: "P17405" },
    { name: "CLN3 (Battenin)", id: "Q13387" },
    { name: "MT-TK (Mitochondrial tRNA-Lys)", id: "P00813" },
    { name: "STXBP1 (Syntaxin Binding Protein 1)", id: "Q15653" },
    { name: "KCNQ5 (Potassium Channel Subfamily KQT Member 5)", id: "Q9NR82" },
    { name: "Gigaxonin (GAN)", id: "Q9UBB6" },
    { name: "Periaxin (PRX)", id: "O00522" },
    { name: "Ataxin-8 (ATXN8)", id: "Q9UBB7" },
    { name: "APTX (Aprataxin)", id: "Q7Z2E3" },
    { name: "MT-ND4 (NADH Dehydrogenase Subunit 4)", id: "P03905" },
    { name: "MT-TL1 (Mitochondrial tRNA-Leu)", id: "P00839" },
    { name: "PDHB (Pyruvate Dehydrogenase Beta Subunit)", id: "P11177" },
    { name: "MID1 (Midline 1)", id: "Q9UHC9" },
    {
      name: "SHANK3 (SH3 and Multiple Ankyrin Repeat Domains 3)",
      id: "Q9BYB0",
    },
  ],
  Hematology: [
    { name: "Hemoglobin Subunit Beta (HBB)", id: "P68871" },
    { name: "Hemoglobin Subunit Alpha-1 (HBA1)", id: "P69905" },
    { name: "Factor VIII (F8)", id: "P00451" },
    { name: "Factor IX (F9)", id: "P00740" },
    { name: "Von Willebrand Factor (VWF)", id: "P04275" },
    { name: "Ankyrin-1 (ANK1)", id: "P16157" },
    { name: "Spectrin Alpha Chain, Erythrocytic 1 (SPTA1)", id: "P02549" },
    { name: "Spectrin Beta Chain, Erythrocytic (SPTB)", id: "P11277" },
    { name: "Glucose-6-Phosphate Dehydrogenase (G6PD)", id: "P11413" },
    { name: "Fanconi Anemia Group C Protein (FANCC)", id: "Q00597" },
    { name: "Fanconi Anemia Group A Protein (FANCA)", id: "O15360" },
    { name: "Band 4.1 Protein (EPB41)", id: "P11171" },
    { name: "Endoglin (ENG)", id: "P17813" },
    { name: "ACVRL1 (Activin A Receptor Type II-Like 1)", id: "P37023" },
    { name: "CDAN1 (Codanin-1)", id: "Q6UB99" },
    { name: "SEC23B (Sec23 Homolog B)", id: "Q15436" },
    { name: "Ribosomal Protein S19 (RPS19)", id: "P39019" },
    { name: "Piezo1 (PIEZO1)", id: "Q92508" },
    { name: "HFE (Homeostatic Iron Regulator Protein)", id: "Q30201" },
    { name: "GP1BA (Platelet Glycoprotein Ib Alpha Chain)", id: "P07359" },
    { name: "ITGA2B (Integrin Alpha-IIb)", id: "P08514" },
    { name: "MYH9 (Myosin Heavy Chain IIA)", id: "P35579" },
    { name: "PIGA (Phosphatidylinositol N-acetylglucosaminyltransferase Subunit A)", id: "P37287" },
    { name: "PKLR (Pyruvate Kinase, Liver and Red Blood Cell)", id: "P30613" },
    { name: "GDF2 (Growth Differentiation Factor 2)", id: "Q9UK05" },
    { name: "FECH (Ferrochelatase)", id: "P22830" },
    { name: "ALAS2 (5-Aminolevulinate Synthase 2)", id: "P22557" },
    { name: "MPL (Thrombopoietin Receptor)", id: "P40238" },
    { name: "ADAMTS13 (A Disintegrin and Metalloproteinase with Thrombospondin Motifs 13)", id: "Q76LX8" },
    { name: "HBBP1 (Hemoglobin Subunit Beta Pseudogene 1)", id: "P02100" },
    { name: "PROC (Protein C)", id: "P04070" },
    { name: "PROS1 (Protein S)", id: "P07225" },
    { name: "SERPINC1 (Antithrombin-III)", id: "P01008" },
    { name: "CYB5R3 (Cytochrome B5 Reductase 3)", id: "P00387" },
    { name: "RHAG (Rh-Associated Glycoprotein)", id: "O43795" },
    { name: "RUNX1 (Runt-Related Transcription Factor 1)", id: "Q01196" },
    { name: "RBM8A (RNA-Binding Motif Protein 8A)", id: "Q9Y5S9" },
    { name: "SERPING1 (C1 Esterase Inhibitor)", id: "P05155" },
    { name: "KIF23 (Kinesin Family Member 23)", id: "Q02241" },
    { name: "KLF1 (Krüppel-Like Factor 1)", id: "Q13351" },
    { name: "SLC4A1 (Band 3 Anion Transporter)", id: "P02730" },
    { name: "HBB (Hemoglobin Subunit Beta)", id: "P68871" },
    { name: "HBA2 (Hemoglobin Subunit Alpha-2)", id: "P69905" },
    { name: "F11 (Coagulation Factor XI)", id: "P03951" },
    { name: "EPOR (Erythropoietin Receptor)", id: "P19235" },
    { name: "VHL (Von Hippel-Lindau Tumor Suppressor)", id: "P40337" },
    { name: "LMAN1 (Lectin Mannose-Binding 1)", id: "P49257" },
    { name: "BMP9 (Bone Morphogenetic Protein 9)", id: "Q9UK05" },
    { name: "THPO (Thrombopoietin)", id: "P40225" }
  ]
};
