// cardiovascularProteins.ts
export interface Protein {
    name: string;
    id: string;
  }
  
  const cardiovascularProteins: Protein[] = [
    { name: "Myosin-7", id: "MYH7: P12883" },
    { name: "Troponin T", id: "TNNT2: P45379" },
    { name: "Troponin I", id: "TNNI3: P19429" },
    { name: "Tropomyosin Alpha-1 Chain", id: "TPM1: P09493" },
    { name: "Myosin Binding Protein C", id: "MYBPC3: Q14896" },
    { name: "Actin, Alpha Cardiac Muscle 1", id: "ACTC1: P68032" },
    { name: "Titin", id: "TTN: Q8WZ42" },
    { name: "Lamin A/C", id: "LMNA: P02545" },
    { name: "Desmin", id: "DES: P17661" },
    { name: "Sodium Voltage-Gated Channel Alpha Subunit 5", id: "SCN5A: Q14524" },
    { name: "Phospholamban", id: "PLN: P26678" },
    { name: "Potassium Voltage-Gated Channel Subfamily Q Member 1", id: "KCNQ1: P51787" },
    { name: "Potassium Voltage-Gated Channel Subfamily H Member 2", id: "KCNH2: Q12809" },
    { name: "Calmodulin 1", id: "CALM1: P62158" },
    { name: "Ankyrin 2", id: "ANK2: Q01638" },
    { name: "GPD1-L", id: "Glycerol-3-phosphate dehydrogenase 1-like: Q8N335" },
    { name: "Calcium Voltage-Gated Channel Subunit Alpha1C", id: "CACNA1C: Q13936" },
    { name: "Ryanodine Receptor 2", id: "RYR2: Q92736" },
    { name: "Calsequestrin 2", id: "CASQ2: O14958" },
    { name: "Fibrillin-1", id: "FBN1: P35555" },
    { name: "Transforming Growth Factor Beta Receptor 1", id: "TGFBR1: P36897" },
    { name: "Transforming Growth Factor Beta Receptor 2", id: "TGFBR2: P37173" },
    { name: "Protein Tyrosine Phosphatase Non-Receptor Type 11", id: "PTPN11: Q06124" },
    { name: "Son of Sevenless Homolog 1", id: "SOS1: Q07889" },
    { name: "Low-Density Lipoprotein Receptor", id: "LDLR: P01130" },
    { name: "Apolipoprotein B", id: "ApoB: P04114" },
    { name: "Proprotein Convertase Subtilisin/Kexin Type 9", id: "PCSK9: Q8NBP7" },
    { name: "Collagen Type III Alpha-1 Chain", id: "COL3A1: P02461" },
    { name: "Myosin Heavy Chain 11", id: "MYH11: P35749" },
    { name: "Actin, Alpha-2, Smooth Muscle, Aorta", id: "ACTA2: P62736" },
    { name: "PRKAG2", id: "Protein Kinase AMP-Activated Non-Catalytic Subunit Gamma 2: Q9UGJ0" },
    { name: "Potassium Voltage-Gated Channel Subfamily J Member 2", id: "KCNJ2: P63252" },
    { name: "Jagged 1", id: "JAG1: P78504" },
    { name: "Alpha-Myosin Heavy Chain", id: "MYH6: P13533" },
    { name: "Cardiac Troponin C", id: "TNNC1: P63316" },
    { name: "Nexilin", id: "NEXN: Q96A32" },
    { name: "Dystrophin", id: "DMD: P11532" },
    { name: "Sarcomeric Alpha-Actinin", id: "ACTN2: P35609" },
    { name: "Potassium Voltage-Gated Channel Subfamily KQT Member 4", id: "KCNQ4: O43524" },
    { name: "Sodium Voltage-Gated Channel Beta Subunit 1", id: "SCN1B: Q07699" },
    { name: "Potassium Voltage-Gated Channel Subfamily KQT Member 2", id: "KCNQ2: O43526" },
    { name: "Glycerol-3-phosphate dehydrogenase 1-like", id: "GPD1L: Q8N335" },
    { name: "Connexin-43", id: "GJA1: P17302" },
    { name: "Smooth Muscle Protein 22-alpha", id: "TAGLN: P37802" },
    { name: "Fibulin-4", id: "EFEMP2: Q12805" },
    { name: "Transforming Growth Factor Beta 2", id: "TGFB2: P61812" },
    { name: "Collagen Type I Alpha 2 Chain", id: "COL1A2: P08123" },
    { name: "LDL Receptor-Related Protein 1", id: "LRP1: Q07954" },
    { name: "Plakoglobin", id: "JUP: P14923" },
    { name: "Desmoplakin", id: "DSP: P15924" },
    { name: "Plakophilin-2", id: "PKP2: Q99959" },
    { name: "Tenascin-X", id: "TNXB: P22105" },
    { name: "RAF1 Proto-Oncogene", id: "RAF1: P04049" },
    { name: "T-box Transcription Factor TBX5", id: "TBX5: Q99593" },
    { name: "NK2 Homeobox 5", id: "NKX2-5: Q9H2E0" },
    { name: "Caveolin-3", id: "CAV3: P56539" },
    { name: "Telethonin", id: "TCAP: Q9UBF9" },
    { name: "Tropomyosin Beta", id: "TPM2: P07951" },
    { name: "Desmin", id: "DES: P17661" },
    { name: "Transmembrane Protein 43", id: "TMEM43: Q9BTV4" },
    { name: "Potassium Channel Subfamily Member 11", id: "KCNJ11: Q14654" },
    { name: "Calcium Voltage-Gated Channel Subunit Beta 2", id: "CACNB2: Q08289" },
    { name: "GATA4", id: "Transcription Factor GATA-4: P43694" },
    { name: "SMAD3", id: "Mothers Against Decapentaplegic Homolog 3: P84022" },
    { name: "Collagen Type IV Alpha 1 Chain", id: "COL4A1: P02462" },
    { name: "Apolipoprotein E", id: "ApoE: P02649" },
    { name: "Zic Family Member 3", id: "ZIC3: Q15915" },
    { name: "TBX1", id: "T-box Transcription Factor TBX1: Q99593" },
    { name: "Bone Morphogenetic Protein Receptor Type 2", id: "BMPR2: Q13873" },
    { name: "Endothelin Receptor Type A", id: "EDNRA: P25101" },
    { name: "PITX2", id: "Paired Like Homeodomain 2: Q99697" },
    { name: "Fibrillin-2", id: "FBN2: P35556" },
    { name: "NEXN", id: "Nexilin: Q96A32" },
    { name: "Filamin C", id: "FLNC: Q14315" },
  ];
  
  export default cardiovascularProteins;
  