// Dummy protein data
export const dummyProteinData = {
    data: {
      protein: {
        id: "P45379",
        name: "TNNT2_HUMAN",
        gene: "CYP3A4",
        sequence: "MSDIEEVVEEYEEEEQEEAAVEEEEDWREDEDEQEEAAEEDAEAEAETEETRAEEDEEEEEAKEAEDGPMEESKPKPRSFMPNLVPPKIPDGERVDFDDIHRKRMEKDLNELQALIEAHFENRKKEEEELVSLKDRIERRRAERAEQQRIRNEREKERQNRLAEERARREEEENRRKAEDEARKKKALSNMMHFGGYIQKQAQTERKSGKRQTEREKKKKILAERRKVLAIDHLNEDQLREKAKELWQSIYNLEAEKFDLQEKFKQQKYEINVLRNRINDNQKVSKTRGKAKVTGRWK",
        metadata: {}
      },
      functional_properties: {
        go_labels: ["0001", "0005", "1234"]
      }
    }
  };
  