// renalProteins.ts

interface Renal {
    name: string;
    id: string;
  }
  
  const Renal: Renal[] = [
    { name: "Polycystin-1 (PKD1)", id: "PKD1" },
    { name: "Polycystin-2 (PKD2)", id: "PKD2" },
    { name: "Fibrocystin/Polyductin (PKHD1)", id: "PKHD1" },
    { name: "Collagen Alpha-3(IV) Chain (COL4A3)", id: "COL4A3" },
    { name: "Collagen Alpha-4(IV) Chain (COL4A4)", id: "COL4A4" },
    { name: "Collagen Alpha-5(IV) Chain (COL4A5)", id: "COL4A5" },
    { name: "Sodium-Potassium-Chloride Cotransporter (NKCC2, SLC12A1)", id: "SLC12A1" },
    { name: "Renal Outer Medullary Potassium Channel (ROMK, KCNJ1)", id: "KCNJ1" },
    { name: "Chloride Channel Kb (CLCNKB)", id: "CLCNKB" },
    { name: "Thiazide-Sensitive Sodium-Chloride Cotransporter (NCC, SLC12A3)", id: "SLC12A3" },
    { name: "Nephrocystin-1 (NPHP1)", id: "NPHP1" },
    { name: "Inversin (NPHP2, INVS)", id: "INVS" },
    { name: "Nephrocystin-3 (NPHP3)", id: "NPHP3" },
    { name: "Nephrocystin-4 (NPHP4)", id: "NPHP4" },
    { name: "Nephrocystin-5 (NPHP5, IQCB1)", id: "NPHP5" },
    { name: "Nephrocystin-6 (NPHP6, CEP290)", id: "NPHP6" },
    { name: "Nephrin (NPHS1)", id: "NPHS1" },
    { name: "Podocin (NPHS2)", id: "NPHS2" },
    { name: "WT1 (Wilms Tumor 1)", id: "WT1" },
    { name: "Alpha-Galactosidase A (GLA)", id: "GLA" },
    { name: "Chloride Channel 5 (CLCN5)", id: "CLCN5" },
    { name: "Low-Density Lipoprotein Receptor-Related Protein 2 (LRP2)", id: "LRP2" },
    { name: "Cystinosin (CTNS)", id: "CTNS" },
    { name: "Ectonucleotide Pyrophosphatase/Phosphodiesterase 1 (ENPP1)", id: "ENPP1" },
    { name: "Sodium-Phosphate Cotransporter 2 (SLC34A1)", id: "SLC34A1" },
    { name: "Alanine-Glyoxylate Aminotransferase (AGXT)", id: "AGXT" },
    { name: "Glyoxylate Reductase/Hydroxypyruvate Reductase (GRHPR)", id: "GRHPR" },
    { name: "Anion Exchanger 1 (AE1, SLC4A1)", id: "SLC4A1" },
    { name: "Carbonic Anhydrase II (CA2)", id: "CA2" },
    { name: "UMOD (Uromodulin)", id: "UMOD" },
    { name: "Tamm-Horsfall Protein (THP)", id: "THP" },
    { name: "CD2-Associated Protein (CD2AP)", id: "CD2AP" },
    { name: "C5ORF42 (Involved in Joubert Syndrome 17)", id: "C5ORF42" },
    { name: "AHI1 (Abelson Helper Integration Site 1)", id: "AHI1" },
    { name: "Meckelin (TMEM67)", id: "TMEM67" },
    { name: "PAX2 (Paired Box Protein Pax-2)", id: "PAX2" },
    { name: "Epithelial Sodium Channel Subunit Beta (SCNN1B)", id: "SCNN1B" },
    { name: "Epithelial Sodium Channel Subunit Gamma (SCNN1G)", id: "SCNN1G" },
    { name: "Phosphatidylinositol 4,5-bisphosphate 5-phosphatase (OCRL)", id: "OCRL" },
    { name: "Calcium-Sensing Receptor (CASR)", id: "CASR" },
    { name: "4-Hydroxy-2-oxoglutarate Aldolase (HOGA1)", id: "HOGA1" },
    { name: "SLC3A1 (Neutral and Basic Amino Acid Transporter)", id: "SLC3A1" },
    { name: "SLC7A9 (B^0,+-Type Amino Acid Transporter)", id: "SLC7A9" },
    { name: "Barttin (BSND)", id: "BSND" },
    { name: "Epithelial Sodium Channel Subunit Alpha (SCNN1A)", id: "SCNN1A" },
    { name: "Hepatocyte Nuclear Factor 1 Beta (HNF1B)", id: "HNF1B" },
    { name: "EYA Transcriptional Coactivator and Phosphatase 1 (EYA1)", id: "EYA1" },
    { name: "Sodium/Potassium-Transporting ATPase Subunit Alpha-1 (ATP1A1)", id: "ATP1A1" },
    { name: "Magnesium Transporter Protein 1 (CNNM2)", id: "CNNM2" },
    { name: "Claudin-16 (CLDN16)", id: "CLDN16" },
    { name: "Phospholipase C Epsilon 1 (PLCE1)", id: "PLCE1" },
    { name: "CEP290 (Centrosomal Protein 290)", id: "CEP290" },
    { name: "NPHP1 (Nephrocystin 1)", id: "NPHP1" },
    { name: "BBS1 (Bardet-Biedl Syndrome 1 Protein)", id: "BBS1" },
    { name: "BBS2 (Bardet-Biedl Syndrome 2 Protein)", id: "BBS2" },
    { name: "Sodium Chloride Cotransporter (SLC12A3, NCC)", id: "SLC12A3" },
    { name: "Collagen Alpha-1(IV) Chain (COL4A1)", id: "COL4A1" },
  ];
  
  export default Renal;
  